version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-backend
    command: python manage.py runserver 0.0.0.0:8080  # Change to 0.0.0.0 to allow external connections
    volumes:
      - ./backend:/app
    working_dir: /app/assignment
    ports:
      - "8080:8080"  # Map local port 8080 to container port 8080
    depends_on:
      - db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: db  # This points to the PostgreSQL service defined as 'db' in docker-compose
      DB_PORT: 5432
      DEBUG: '1'  # For development, in production set this to '0'
      ALLOWED_HOSTS: '0.0.0.0,localhost'  # Adjust this for production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs-frontend
    volumes:
      - ./frontend/assignment_frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
